// Foreign crate reexports for use in macros. Do not touch in your own applications.
pub mod reex {
    pub use bincode;
    pub use wapc_guest;
}
/// Types related to HTTP handling. 
pub mod http {
    pub use zhur_invk::http::*;
}
/// Invocation error reexport.
pub mod invk {
    pub use zhur_invk::InvocationError;
}
/// A basic, barebones "web framework" to get you started.
pub mod web;
/// Autogenerated boilerplate for waPC.
mod bplate;
/// External services your apps can call.
pub mod svc;